id,module,name,file,doc,markers,status,message,duration
functional_correctness_test_folder/post_cut-off/rag/meta-llama/partial_docstr/test_snippet_183.py::test_case_0,functional_correctness_test_folder.post_cut-off.rag.meta-llama.partial_docstr.test_snippet_183,test_case_0,functional_correctness_test_folder/post_cut-off/rag/meta-llama/partial_docstr/test_snippet_183.py,,,failed,TypeError: InferenceConfig.__init__() got an unexpected keyword argument 'max_steps',9.658292401582003e-05
functional_correctness_test_folder/post_cut-off/rag/meta-llama/partial_docstr/test_snippet_183.py::test_case_1,functional_correctness_test_folder.post_cut-off.rag.meta-llama.partial_docstr.test_snippet_183,test_case_1,functional_correctness_test_folder/post_cut-off/rag/meta-llama/partial_docstr/test_snippet_183.py,,,failed,TypeError: InferenceConfig.__init__() got an unexpected keyword argument 'server_max_workers',0.00010054104495793581
functional_correctness_test_folder/post_cut-off/rag/meta-llama/partial_docstr/test_snippet_183.py::test_case_2,functional_correctness_test_folder.post_cut-off.rag.meta-llama.partial_docstr.test_snippet_183,test_case_2,functional_correctness_test_folder/post_cut-off/rag/meta-llama/partial_docstr/test_snippet_183.py,,,failed,TypeError: InferenceConfig.__init__() got an unexpected keyword argument 'split',8.962501306086779e-05
