id,module,name,file,doc,markers,status,message,duration
functional_correctness_test_folder/post_cut-off/rag/gpt-4.1/no_docstr/test_snippet_345.py::test_case_0,functional_correctness_test_folder.post_cut-off.rag.gpt-4.1.no_docstr.test_snippet_345,test_case_0,functional_correctness_test_folder/post_cut-off/rag/gpt-4.1/no_docstr/test_snippet_345.py,,,failed,AttributeError: 'EnhancedUser' object has no attribute 'username',0.00011100003030151129
functional_correctness_test_folder/post_cut-off/rag/gpt-4.1/no_docstr/test_snippet_345.py::test_case_1,functional_correctness_test_folder.post_cut-off.rag.gpt-4.1.no_docstr.test_snippet_345,test_case_1,functional_correctness_test_folder/post_cut-off/rag/gpt-4.1/no_docstr/test_snippet_345.py,,,failed,AttributeError: 'EnhancedUser' object has no attribute 'username',0.00012649991549551487
functional_correctness_test_folder/post_cut-off/rag/gpt-4.1/no_docstr/test_snippet_345.py::test_case_2,functional_correctness_test_folder.post_cut-off.rag.gpt-4.1.no_docstr.test_snippet_345,test_case_2,functional_correctness_test_folder/post_cut-off/rag/gpt-4.1/no_docstr/test_snippet_345.py,,,failed,AttributeError: 'EnhancedUser' object has no attribute 'username',0.0002947499742731452
functional_correctness_test_folder/post_cut-off/rag/gpt-4.1/no_docstr/test_snippet_345.py::test_case_3,functional_correctness_test_folder.post_cut-off.rag.gpt-4.1.no_docstr.test_snippet_345,test_case_3,functional_correctness_test_folder/post_cut-off/rag/gpt-4.1/no_docstr/test_snippet_345.py,,,failed,TypeError: EnhancedUser.__init__() got an unexpected keyword argument 'avatar',0.0010357090504840016
